language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt

virtualenv:
  system_site_packages: true

# command to run tests
script:
  - python manage.py test kidsbook/group/
  - python manage.py test kidsbook/user/
  - python manage.py test kidsbook/batch/
