language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  - postgresql

addons:
  postgresql: "10"

before_script:
  - psql -U postgres -c "CREATE DATABASE app_db;"
  - psql -U postgres -c "CREATE USER app_user WITH PASSWORD 'password';"
  - psql -U postgres -c "ALTER ROLE app_user SET client_encoding TO 'utf8';"
  - psql -U postgres -c "ALTER ROLE app_user SET default_transaction_isolation TO 'read committed';"
  - psql -U postgres -c "ALTER ROLE app_user SET timezone TO 'UTC';"
  - psql -U postgres -c "ALTER USER app_user CREATEDB;"
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE app_db TO app_user;"
  - rm -rf kidsbook/migrations
  - python manage.py makemigrations kidsbook
  - python manage.py migrate


# command to run tests
script:
  - python manage.py test kidsbook/group/
  - python manage.py test kidsbook/user/
  - python manage.py test kidsbook/batch/
