language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -U postgres -c "create database app_db;CREATE DATABASE app_db; \
    CREATE USER app_user WITH PASSWORD 'password'; \
    ALTER ROLE app_user SET client_encoding TO 'utf8'; \
    ALTER ROLE app_user SET default_transaction_isolation TO 'read committed'; \
    ALTER ROLE app_user SET timezone TO 'UTC'; \
    ALTER USER app_user CREATEDB; \
    GRANT ALL PRIVILEGES ON DATABASE app_db TO app_user;"

# command to run tests
script:
  - python manage.py test kidsbook/group/
  - python manage.py test kidsbook/user/
  - python manage.py test kidsbook/batch/
